### ISSUE TITLE
Uncaught TypeError: $(...).editable is not a function

### ISSUE THREAD

**Issue by wiad** [ATIX-AG/foreman_snapshot_management#60]
After updating to Foreman 2.3 I get this error when loading the host detail page. 

Might be related to https://projects.theforeman.org/issues/29257

**Comment by wiad** [comment]
This error shows when clicking on the `Snapshots` tab in the host detail page on a host with a current snapshot.

**Comment by m-bucher** [comment]
Thanks for reporting this.
I looked into it and, as you correctly deduced, this is related to the ui-helper-functions having been "removed" and migrated to the new react ui-implementation.

Unfortunately, this is not easily solvable, because we cannot just use the part of the new react implementation we need.
This might be a good opportunity to look into re-implementing the UI of this plugin in react.
But I cannot say, when anyone will be able to implement this.

A quick fix might be to remove the ability to change the name or description of an existing Snapshot completely.
This can be done by removing these two `if`-statements and only keep the instructions from the respective `else`-blocks:
* https://github.com/ATIX-AG/foreman_snapshot_management/blob/2d8237650718efa8e4338558864efebb4d53f393/app/views/foreman_snapshot_management/snapshots/_index.html.erb#L35
* https://github.com/ATIX-AG/foreman_snapshot_management/blob/2d8237650718efa8e4338558864efebb4d53f393/app/views/foreman_snapshot_management/snapshots/_index.html.erb#L43

**Comment by wiad** [comment]
The quick fix works, thank you! We can live without that functionality.
